# Generated by Django 4.1.7 on 2023-03-12 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComputadoresBackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computadora',
            name='fecha_venta',
            field=models.DateField(verbose_name='fecha de venta'),
        ),
    ]
