# Generated by Django 4.1.7 on 2023-03-12 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComputadoresBackend', '0002_alter_computadora_fecha_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computadora',
            name='fecha_venta',
            field=models.DateTimeField(verbose_name='fecha de venta'),
        ),
    ]
